@startuml erd-ugc

skinparam linetype ortho

title
    Диаграмма сущностей БД сервиса UGC
end title

entity "Пользователь" as cred {
    id : uuid NOT NULL
    --
    ...
}

entity "Пост" as post {
    post_id : uuid NOT NULL
    --
    author_id : uuid NOT NULL REFERENCES creds (id)
    content : text NOT NULL
    create_timestamp : timestamp NOT NULL
    update_timestamp : timestamp
}

entity "Комментарий" as comment {
    id : serial NOT NULL
    --
    author_id : uuid NOT NULL REFERENCES creds (id)
    parent_post_id : uuid REFERENCES post (id)
    parent_comment_id : uuid REFERENCES comment (id)
    content : text NOT NULL
    create_timestamp : timestamp NOT NULL
    update_timestamp : timestamp
    --
    CHECK (parent_post_id IS NOT NULL
    OR parent_comment_id IS NOT NULL)
}

cred ||--o{ post
post ||--o{ comment
comment ||--o{ comment

@enduml
