@startuml erd-main

skinparam linetype ortho

entity "Живой человек" as human {}

entity "Кредитка" as cred {
    id : uuid NOT NULL
    --
    login : varchar(255) UNIQUE NOT NULL
    salt bytea NOT NULL
    password text NOT NULL
}

entity "Данные" as data {
    id : uuid NOT NULL
    --
    name : varchar(255) NOT NULL
    surname : varchar(255) NOT NULL
    birthdate : date NOT NULL
    email : varchar(255) NOT NULL
    phone : varchar(32) NOT NULL
}

human ||--o{ cred
cred ||--|| data

@enduml
